#Hugo configuration
title = "Test Google IMA"
baseURL = "https:\/\/www.ima.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758403"
subfolder = ""
